# Generated by Django 5.2 on 2025-05-28 19:14

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='Title')),
                ('url', models.URLField(unique=True, verbose_name='Address')),
                ('username', models.CharField(blank=True, max_length=68, null=True, verbose_name='Username')),
                ('password', encrypted_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Websites',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Address')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Description')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='favlinks.website')),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
    ]
