# Generated by Django 5.2 on 2025-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favlinks', '0002_category_link_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
